# fastapi-deployment.yaml (Versi yang Benar dan Bersih)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-sentiment
  template:
    metadata:
      labels:
        app: fastapi-sentiment
    spec:
      containers:
      - name: fastapi-sentiment-app
        image: sentiment-api:v1.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: fastapi-secrets
        env:
        - name: REDIS_URL
          value: "redis://redis-service:6379"